antibiotic_metadata = {
    "5-Fluorocytosine": {
        "ATC2": "J02",
        "ATC3": "J02A",
        "ATC4": "J02AX",
        "mechanism": "antifungal",
        "beta_lactamase_inhibitor": 0,
    },
    "Amikacin": {
        "ATC2": "J01",
        "ATC3": "J01G",
        "ATC4": "J01GB",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Amoxicillin": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CA",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Amoxicillin-Clavulanic acid": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CR",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 1,
    },
    "Amoxicillin-Clavulanic acid_uncomplicated_HWI": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CR",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 1,
    },
    "Amphotericin B": {
        "ATC2": "J02",
        "ATC3": "J02A",
        "ATC4": "J02AA",
        "mechanism": "membrane",
        "beta_lactamase_inhibitor": 0,
    },
    "Ampicillin": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CA",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Ampicillin-Sulbactam": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CR",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 1,
    },
    "Anidulafungin": {
        "ATC2": "J02",
        "ATC3": "J02A",
        "ATC4": "J02AX",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Azithromycin": {
        "ATC2": "J01",
        "ATC3": "J01F",
        "ATC4": "J01FA",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Aztreonam": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DF",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Bacitracin": {
        "ATC2": "J01",
        "ATC3": "J01X",
        "ATC4": "J01XX",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Benzylpenicillin": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CE",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Benzylpenicillin_others": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CE",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Benzylpenicillin_with_meningitis": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CE",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Benzylpenicillin_with_pneumonia": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CE",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Caspofungin": {
        "ATC2": "J02",
        "ATC3": "J02A",
        "ATC4": "J02AX",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Cefalotin-Cefazolin": {
        "ATC2": None,
        "ATC3": None,
        "ATC4": None,
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Cefazolin": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DB",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Cefepime": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DE",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Cefixime": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DD",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Cefotaxime": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DD",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Cefoxitin": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DC",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Cefoxitin_screen": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DC",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Cefpodoxime": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DD",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Ceftarolin": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DI",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Ceftazidime": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DD",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Ceftazidime-Avibactam": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DD",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 1,
    },
    "Ceftobiprole": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DI",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Ceftolozane-Tazobactam": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DI",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 1,
    },
    "Ceftriaxone": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DD",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Cefuroxime": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DC",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Cefuroxime.1": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DC",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Chloramphenicol": {
        "ATC2": "J01",
        "ATC3": "J01B",
        "ATC4": "J01BA",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Ciprofloxacin": {
        "ATC2": "J01",
        "ATC3": "J01M",
        "ATC4": "J01MA",
        "mechanism": "DNA_RNA",
        "beta_lactamase_inhibitor": 0,
    },
    "Clarithromycin": {
        "ATC2": "J01",
        "ATC3": "J01F",
        "ATC4": "J01FA",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Clindamycin": {
        "ATC2": "J01",
        "ATC3": "J01F",
        "ATC4": "J01FF",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Clindamycin_induced": {
        "ATC2": "J01",
        "ATC3": "J01F",
        "ATC4": "J01FF",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Colistin": {
        "ATC2": "J01",
        "ATC3": "J01X",
        "ATC4": "J01XB",
        "mechanism": "membrane",
        "beta_lactamase_inhibitor": 0,
    },
    "Cotrimoxazol": {
        "ATC2": "J01",
        "ATC3": "J01E",
        "ATC4": "J01EE",
        "mechanism": "metabolic",
        "beta_lactamase_inhibitor": 0,
    },
    "Cotrimoxazole": {
        "ATC2": "J01",
        "ATC3": "J01E",
        "ATC4": "J01EE",
        "mechanism": "metabolic",
        "beta_lactamase_inhibitor": 0,
    },
    "Daptomycin": {
        "ATC2": "J01",
        "ATC3": "J01X",
        "ATC4": "J01XX",
        "mechanism": "membrane",
        "beta_lactamase_inhibitor": 0,
    },
    "Doxycycline": {
        "ATC2": "J01",
        "ATC3": "J01A",
        "ATC4": "J01AA",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Ertapenem": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DH",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Erythromycin": {
        "ATC2": "J01",
        "ATC3": "J01F",
        "ATC4": "J01FA",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Ethambutol_5mg-l": {
        "ATC2": "J04",
        "ATC3": "J04A",
        "ATC4": "J04AK",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Fluconazole": {
        "ATC2": "J02",
        "ATC3": "J02A",
        "ATC4": "J02AC",
        "mechanism": "membrane",
        "beta_lactamase_inhibitor": 0,
    },
    "Fosfomycin": {
        "ATC2": "J01",
        "ATC3": "J01X",
        "ATC4": "J01XX",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Fusidic acid": {
        "ATC2": "J01",
        "ATC3": "J01X",
        "ATC4": "J01XC",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Gentamicin": {
        "ATC2": "J01",
        "ATC3": "J01G",
        "ATC4": "J01GB",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Gentamicin_high_level": {
        "ATC2": "J01",
        "ATC3": "J01G",
        "ATC4": "J01GB",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Imipenem": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DH",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Isavuconazole": {
        "ATC2": "J02",
        "ATC3": "J02A",
        "ATC4": "J02AC",
        "mechanism": "membrane",
        "beta_lactamase_inhibitor": 0,
    },
    "Isoniazid_.1mg-l": {
        "ATC2": "J04",
        "ATC3": "J04A",
        "ATC4": "J04AC",
        "mechanism": "metabolic",
        "beta_lactamase_inhibitor": 0,
    },
    "Isoniazid_.4mg-l": {
        "ATC2": "J04",
        "ATC3": "J04A",
        "ATC4": "J04AC",
        "mechanism": "metabolic",
        "beta_lactamase_inhibitor": 0,
    },
    "Itraconazole": {
        "ATC2": "J02",
        "ATC3": "J02A",
        "ATC4": "J02AC",
        "mechanism": "membrane",
        "beta_lactamase_inhibitor": 0,
    },
    "Levofloxacin": {
        "ATC2": "J01",
        "ATC3": "J01M",
        "ATC4": "J01MA",
        "mechanism": "DNA_RNA",
        "beta_lactamase_inhibitor": 0,
    },
    "Linezolid": {
        "ATC2": "J01",
        "ATC3": "J01X",
        "ATC4": "J01XX",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "MRSA": {
        "ATC2": None,
        "ATC3": None,
        "ATC4": None,
        "mechanism": None,
        "beta_lactamase_inhibitor": None,
    },
    "Meropenem": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DH",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Meropenem-Vaborbactam": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DH",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 1,
    },
    "Meropenem_with_meningitis": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DH",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Meropenem_with_pneumonia": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DH",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Meropenem_without_meningitis": {
        "ATC2": "J01",
        "ATC3": "J01D",
        "ATC4": "J01DH",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Metronidazole": {
        "ATC2": "J01",
        "ATC3": "J01X",
        "ATC4": "J01XD",
        "mechanism": "DNA_RNA",
        "beta_lactamase_inhibitor": 0,
    },
    "Micafungin": {
        "ATC2": "J02",
        "ATC3": "J02A",
        "ATC4": "J02AX",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Minocycline": {
        "ATC2": "J01",
        "ATC3": "J01A",
        "ATC4": "J01AA",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Moxifloxacin": {
        "ATC2": "J01",
        "ATC3": "J01M",
        "ATC4": "J01MA",
        "mechanism": "DNA_RNA",
        "beta_lactamase_inhibitor": 0,
    },
    "Mupirocin": {
        "ATC2": "D06",
        "ATC3": "D06A",
        "ATC4": "D06AX",
        "mechanism": "antifungal",
        "beta_lactamase_inhibitor": 0,
    },
    "Nitrofurantoin": {
        "ATC2": "J01",
        "ATC3": "J01X",
        "ATC4": "J01XE",
        "mechanism": "DNA_RNA",
        "beta_lactamase_inhibitor": 0,
    },
    "Norfloxacin": {
        "ATC2": "J01",
        "ATC3": "J01M",
        "ATC4": "J01MA",
        "mechanism": "DNA_RNA",
        "beta_lactamase_inhibitor": 0,
    },
    "Novobiocin": {
        "ATC2": None,
        "ATC3": None,
        "ATC4": None,
        "mechanism": "DNA_gyrase",
        "beta_lactamase_inhibitor": 0,
    },
    "Ofloxacin": {
        "ATC2": "J01",
        "ATC3": "J01M",
        "ATC4": "J01MA",
        "mechanism": "DNA_RNA",
        "beta_lactamase_inhibitor": 0,
    },
    "Oxacillin": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CF",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Pefloxacin": {
        "ATC2": "J01",
        "ATC3": "J01M",
        "ATC4": "J01MA",
        "mechanism": "DNA_RNA",
        "beta_lactamase_inhibitor": 0,
    },
    "Penicillin": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CA",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Penicillin_with_endokarditis": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CA",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Penicillin_with_meningitis": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CA",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Penicillin_with_other_infections": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CA",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Penicillin_with_pneumonia": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CA",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Penicillin_without_endokarditis": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CA",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Penicillin_without_meningitis": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CA",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Piperacillin": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CA",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Piperacillin-Tazobactam": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CR",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 1,
    },
    "Polymyxin B": {
        "ATC2": "J01",
        "ATC3": "J01X",
        "ATC4": "J01XB",
        "mechanism": "membrane",
        "beta_lactamase_inhibitor": 0,
    },
    "Posaconazole": {
        "ATC2": "J02",
        "ATC3": "J02A",
        "ATC4": "J02AC",
        "mechanism": "membrane",
        "beta_lactamase_inhibitor": 0,
    },
    "Pristinamycin": {
        "ATC2": "J01",
        "ATC3": "J01F",
        "ATC4": "J01FG",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Pyrazinamide": {
        "ATC2": "J04",
        "ATC3": "J04A",
        "ATC4": "J04AK",
        "mechanism": "metabolic",
        "beta_lactamase_inhibitor": 0,
    },
    "Rifampicin": {
        "ATC2": "J04",
        "ATC3": "J04A",
        "ATC4": "J04AB",
        "mechanism": "DNA_RNA",
        "beta_lactamase_inhibitor": 0,
    },
    "Rifampicin_1mg-l": {
        "ATC2": "J04",
        "ATC3": "J04A",
        "ATC4": "J04AB",
        "mechanism": "DNA_RNA",
        "beta_lactamase_inhibitor": 0,
    },
    "Sparfloxacin": {
        "ATC2": "J01",
        "ATC3": "J01M",
        "ATC4": "J01MA",
        "mechanism": "DNA_RNA",
        "beta_lactamase_inhibitor": 0,
    },
    "Strepomycin_high_level": {
        "ATC2": "J01",
        "ATC3": "J01G",
        "ATC4": "J01GA",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Streptomycin": {
        "ATC2": "J01",
        "ATC3": "J01G",
        "ATC4": "J01GA",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Teicoplanin": {
        "ATC2": "J01",
        "ATC3": "J01X",
        "ATC4": "J01XA",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Teicoplanin_GRD": {
        "ATC2": "J01",
        "ATC3": "J01X",
        "ATC4": "J01XA",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Telithromycin": {
        "ATC2": "J01",
        "ATC3": "J01F",
        "ATC4": "J01FA",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Tetracycline": {
        "ATC2": "J01",
        "ATC3": "J01A",
        "ATC4": "J01AA",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Ticarcillin": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CA",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Ticarcillin-Clavulan acid": {
        "ATC2": "J01",
        "ATC3": "J01C",
        "ATC4": "J01CR",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 1,
    },
    "Tigecycline": {
        "ATC2": "J01",
        "ATC3": "J01A",
        "ATC4": "J01AA",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Tobramycin": {
        "ATC2": "J01",
        "ATC3": "J01G",
        "ATC4": "J01GB",
        "mechanism": "protein_synthesis",
        "beta_lactamase_inhibitor": 0,
    },
    "Vancomycin": {
        "ATC2": "J01",
        "ATC3": "J01X",
        "ATC4": "J01XA",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Vancomycin_GRD": {
        "ATC2": "J01",
        "ATC3": "J01X",
        "ATC4": "J01XA",
        "mechanism": "cell_wall",
        "beta_lactamase_inhibitor": 0,
    },
    "Voriconazole": {
        "ATC2": "J02",
        "ATC3": "J02A",
        "ATC4": "J02AC",
        "mechanism": "membrane",
        "beta_lactamase_inhibitor": 0,
    },
}